export { default as Carrot } from './carrots.svg';
export { default as Cauliflower } from './cauliflower.svg';
export { default as Onion } from './onions.svg';
export { default as sampleImage } from './sampleImage.png';
export { default as Search } from './search.svg';
export { default as Help } from './help.svg';
export { default as Profile } from './profile.svg';
export { default as Logo } from './logo.svg';
export { default as Thankimg } from './thankyou_img.png';